# Generated by Django 3.0.4 on 2021-02-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='dhanlaxmi',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='disawer',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='fridabad',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='gaziyabad',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
